server:
  port: 8030
spring:
  ###数据库
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/demo_xxxcloud_alibaba?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root

######日志
logging:
  #日志配置的文件位置，如果是：resource下的log4j2-spring.xml则不用配置
  config: classpath:log/log4j2-dev.xml
  #包配置及日志级别
  level:
    com.lhl: trace
