spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
