spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@

######mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lhl.xxxcloud.entity
