server:
  port: 88
spring:
  cloud:
    nacos:
      discovery:
        namespace: dceacf9e-5e64-4935-af3f-cd7f567331a5
      server-addr: ${NACOS_HOST:127.0.0.1}:8848 # nacos地址
    gateway:
      routes:
        - id: xxxcloud-service-order # 路由标示，必须唯一
          uri: lb://xxxcloud-service-order # 路由的目标地址
          filters:
            - StripPrefix=1 #截去前面n个路径，剩余部分和uri的值拼接作为转发地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/xxxcloud-service-order/** # 路径断言，判断路径是否是以/item开头，如果是则符合


        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/order/**,/pay/**
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/user/**,/address/**
        - id: searchservice
          uri: lb://searchservice
          predicates:
            - Path=/search/**
      default-filters:
        - AddRequestHeader=authorization, 2//添加网关的请求头
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              //请求地址
            allowedMethods: #请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
